# Generated by Django 5.2.8 on 2025-11-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('tag', models.CharField()),
                ('timestamp', models.BigIntegerField()),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('userId', 'movieId', 'tag'), name='unique_tag')],
            },
        ),
    ]
