# Generated by Django 5.2.8 on 2025-11-18 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag',
        ),
        migrations.AlterField(
            model_name='tag',
            name='movieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=255),
        ),
    ]
